quiet on


REM <File Open>    
hload C:\Users\dong\PPC32-Debug-MPC560\workdir\ppc32-cpu-test\RAM\ppc32-cpu-test.elf
gotil main
quiet off


REM <Modify Register value>
R7 $00000300
R8 $00000400


logfile C:\Users\dong\PPC32-Debug-MPC560\debug-output\before_snapshot.log

REM <Before test-intruction>
snapshot

lf

logfile C:\Users\dong\PPC32-Debug-MPC560\debug-output\after_snapshot.log
REM <Run test-intruction>
step
snapshot
lf

quit